### ISSUE TITLE
Make a Capacitor 3 Plugin Template

### ISSUE THREAD

**Issue by thomasvidas** [capacitor-community/.github#5]
By augmenting this existing repository, we could add the following subfolders as sort of a "best practice" for creating Capacitor plugins in the style of `@capacitor-community/http` by including the plugin code and the example in the same repo while only distributing the plugin code; allowing for better DX when starting and collaborating on projects.

**Comment by jcesarmobile** [comment]
Closing as we have the plugin generator which creates the plugins with the recommended folders
https://github.com/ionic-team/create-capacitor-plugin
